### ISSUE TITLE
abstract configurations

### ISSUE THREAD

**Issue by willkg** [mozilla/spicedham#13]
Django stores configurations in settings, but other systems store configuration information in other places.

It'd be good to abstract configuration so that there's a specified configuration loader which loads the configuration and returns a configuration object which then gets used where configuration is needed.

**Comment by iankronquist** [comment]
Done. Configuration loaders will inherit from `BaseConfig`. That class's `load_config` method is expected to return a dict. Plugins are expected to provide sane defaults so it could potentially run without a config loader. I have a subclass of this for django, but not in the current branch.
