### ISSUE TITLE
TypeError: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by willkg** [mozilla/spicedham#21]
https://github.com/mozilla/spicedham/blob/master/spicedham/bayes.py#L42

`total` there can be None since `get_key` returns None by default of the thing isn't in the store. If `total` is None, then this kicks up a `TypeError`.

We should either fix this to handle when `total = None` or change the `get_key` call to return a more appropriate default that allows this code to work.

**Comment by willkg** [comment]
Oops--more resilient link is this one:

https://github.com/mozilla/spicedham/blob/5be9b4afb136ce052ffefef8540e62d93abc317c/spicedham/bayes.py#L42

**Comment by willkg** [comment]
I'm also getting a ZeroDivisonError:

```
  File "/home/willkg/mozilla/fjord/vendor/src/spicedham/spicedham/__init__.py", line 73, in classify
    value = plugin.classify(classification_data)
  File "/home/willkg/mozilla/fjord/vendor/src/spicedham/spicedham/bayes.py", line 62, in classify
    pWordGivenHam = (word['numTotal'] - word['numSpam']) / (total['numTotal'] - total['numSpam'])
ZeroDivisionError: division by zero
```

**Comment by iankronquist** [comment]
So really this will only happen if the classifier has been called before training, or there is no training data. This is kind of silly. I could check that total != 0, and if so throw an exception.

**Comment by willkg** [comment]
This happens in tests because they use a clean db.
