### ISSUE TITLE
abstract out the parser

### ISSUE THREAD

**Issue by willkg** [mozilla/spicedham#22]
Took me a while to figure out that "train data" and "classify data" is a list of strings which is actually a list of tokens from the original string being used for training/classification.

E.g. if you had a description "Firefox is the best!", the training data should be a list of tokens from that string and that spicedham doesn't do any tokenization.

I contend that spicedham should do tokenization and that the tokenizer should be pluggable like the configuration parser.

**Comment by iankronquist** [comment]
PR #23
