### ISSUE TITLE
insight into scoring

### ISSUE THREAD

**Issue by willkg** [mozilla/spicedham#27]
Right now, you run a piece of text through spicedham and you get back a float and that's it. There's no way to elicit more information from spicedham about the scoring breakdown or what influenced the score.

I think we could do one of a couple of things.
1. add logging to spicedham so that it logs all the data and then the user can run text through spicedham and read through the logs
2. change `classify` so that it returns an instance which contains the complete score breakdown as well as the final score
3. create a new method called something like `explain` which returns the complete score breakdown

For plugin simplicity I think we should do 2 or alternatively, Spicedham could have a `classify` which pulls just the score from the end result and returns that and could have an `explain` which returns the data raw. Then we change plugins so that they're always returning the score and breakdown. That way we don't have to implement multiple API methods for plugins plus they're easier to test/introspect later on.

Other ideas?

**Comment by iankronquist** [comment]
Bayes logging #28 does part 1.
