### ISSUE TITLE
Multiple back ends

### ISSUE THREAD

**Issue by iankronquist** [mozilla/spicedham#3]
We may want multiple back ends. Examples include:
- The django orm
- Flat files
- A key value store like memcached
- Something else?

**Comment by iankronquist** [comment]
I now have infrastructure to support multiple back ends, but only one such back end.

**Comment by iankronquist** [comment]
Once the Fjord specific backend lands this may no longer be necessary. If kitsune want's to use spicedham it will need its own backend. I think we can close this issue.

**Comment by willkg** [comment]
I think supporting multiple backends is prudent still. If nothing else, having a flat file backend would be handy.
