### ISSUE TITLE
create better coupling for backends

### ISSUE THREAD

**Issue by willkg** [mozilla/spicedham#7]
https://github.com/mozilla/spicedham/blob/master/spicedham/backend.py#L5

That will end up requiring someone to have all the dependencies for all the backends installed in order to use the one they're looking for.

Instead of doing that, it's better to have the user specify which backend to use as a string to the Python module, then have `load_backend` import the module the user specified, instantiate and configure the backend and then return the Backend object.

So for the sqlalchemy backend, the user would specify this in the configuration:

```
'spicedham.sqlalchemywrapper:SqlAlchemyWrapper'
```

Then `load_backend` would do something like this:

```
def load_backend():
    global _backend
    if _backend:
        # FIXME: This caching of the backend globally requires that the backend be
        # thread-safe and also means this library can only use one backend at a time.
        return _backend

    config = load_config()
    module, cls = config['backend'].split(':')

    cls = __import__(config['backend'], globals(), locals(), [cls], -1)
    _backend = cls()
    return _backend
```

**Comment by willkg** [comment]
That code isn't tested. I'm pretty sure it's either right or pretty close to it. It uses `__import__`:

https://docs.python.org/2/library/functions.html#__import__

**Comment by iankronquist** [comment]
All of this has completely changed, and _load_backend is now part of the spicedham class.
Now, to specify the backend you put something like this in your config:

``` python
SETTINGS = {
    'backend': 'BackendClassName',
}
```
