### ISSUE TITLE
nix the "really" arg

### ISSUE THREAD

**Issue by willkg** [mozilla/spicedham#9]
https://github.com/mozilla/spicedham/blob/master/spicedham/basewrapper.py#L8

You don't need the "really" arg. This isn't a command line interface--it's an API. Generally it doesn't help to have things like that.

For example, as written, if "really" isn't True-ish, then the function does nothing and doesn't say anything about how it just did nothing. That doesn't really make a lot of sense and is likely to just create programming errors that are hard to reason about.

**Comment by iankronquist** [comment]
Okay, nixed in the 'pluggability' branch.
